### ISSUE TITLE
Add Sensor support

### ISSUE THREAD

**Issue by hillaliy** [ayavilevich/Tasmota#2]
Hi
first thanks for you work.
Can you add support for temperature sensor?

**Comment by ayavilevich** [comment]
Hi @hillaliy 

This is a fork of Tasmota specifically to deal with issues of ACs with power toggle operation.

I am not sure I understand your request. It doesn't seem relevant here.

Regardless, the Tasmota firmware already supports a long list of sensors, including temperature sensors.
See https://tasmota.github.io/docs/Supported-Peripherals/

**Comment by hillaliy** [comment]
I know it's for fix Ac's power issues. But on the configure module on your image there isn't option to choose temperature sensor.

**Comment by ayavilevich** [comment]
Ok, I think I understand you now.

Do you mean you need the tasmota-ircustom build instead of tasmota-ir? To have support for some sensor?

**Comment by hillaliy** [comment]
yes, but the Tasmota-ircustom have power issue with airwell HVAC

**Comment by hillaliy** [comment]
that why I use your image

**Comment by ayavilevich** [comment]
got you.
added ircustom build with the fixes.
see https://github.com/ayavilevich/Tasmota/releases/download/v0.4/firmware-ircustom-state-sync.bin.gz

**Comment by hillaliy** [comment]
Thanks

**Comment by ayavilevich** [comment]
@hillaliy I don't have a system to test this. I just built it. Use on your own risk. Let me know here how it works.

**Comment by hillaliy** [comment]
I'll try now

**Comment by ayavilevich** [comment]
Do you use a custom built transmitter/receiver or a commercial product? Which one?

**Comment by hillaliy** [comment]
I use custom build ESP8266

**Comment by hillaliy** [comment]
it's work
